# Generated by Django 5.1.1 on 2024-10-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_favorite_book_wrap_favorite_booklet_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ebook'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
