# Generated by Django 5.1.1 on 2024-10-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='school_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.schooloffice'),
        ),
    ]
