# Generated by Django 5.1.1 on 2024-10-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_favorite_school_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='school_office',
        ),
    ]
